pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('SonarQube analysis') {
            steps {
                withSonarQubeEnv(installationName: 'SonarScanner') {
                    sh 'mvn clean verify sonar:sonar'
                }
            }
        }
    }
}
// pipeline {
//     agent any
//     stages {
//         stage("Clean Up") {
//             steps {
//                 deleteDir()
//             }
//         }
//         stage("Clone Repo") {
//             steps {
//                 sh "git clone https://github.com/RidaAbrahams/simple-java-maven-app.git"
//             }
//         }
//         stage("Build") {
//             steps {
//                 dir("simple-java-maven-app") {
//                     sh "mvn clean install"
//                 }
//             }
//         }
//         stage("Test") {
//             steps {
//                 dir("simple-java-maven-app") {
//                     sh "mvn test"
//                 }
//             }
//         }
//     }
// }
